const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Header
    'nav.home': 'Trang chủ',
    'nav.services': 'Dịch vụ',
    'nav.portfolio': 'Portfolio',
    'nav.about': 'Về chúng tôi',
    'nav.blog': 'Blog',
    'nav.contact': 'Liên hệ',
    
    // Hero
    'hero.title1': 'B2B Marketing Agency',
    'hero.title2': 'Hàng Đầu Việt Nam',
    'hero.title3': 'Dịch Vụ Marketing Toàn Diện',
    'hero.description': 'Công ty marketing B2B chuyên cung cấp',
    'hero.description.highlight1': 'giải pháp marketing cho doanh nghiệp',
    'hero.description.text': 'tư vấn chiến lược marketing, và',
    'hero.description.highlight2': 'dịch vụ marketing số toàn diện',
    'hero.description.end': 'cho thị trường B2B Việt Nam.',
    'hero.cta.consultation': 'Nhận Tư Vấn Marketing B2B Miễn Phí',
    'hero.cta.services': 'Xem Dịch Vụ Marketing',
    'hero.stats.automations': 'Tự Động Hóa Thành Công',
    'hero.stats.roi': 'Tăng Trưởng ROI',
    'hero.stats.engagement': 'Chăm Sóc Khách Hàng',
    
    // Services
    'services.title': 'Dịch Vụ Của Chúng Tôi',
    'services.subtitle': 'Giải pháp tự động hóa toàn diện cho doanh nghiệp',
    'services.chatbot.title': 'Chatbot AI & Zalo OA',
    'services.chatbot.desc': 'Tự động hóa chăm sóc khách hàng 24/7',
    'services.automation.title': 'Tự Động Hóa Quy Trình',
    'services.automation.desc': 'Tối ưu hóa quy trình làm việc và tăng hiệu suất',
    'services.n8n.title': 'N8N Workflow',
    'services.n8n.desc': 'Kết nối và tự động hóa ứng dụng',
    'services.ai.title': 'Tích Hợp AI',
    'services.ai.desc': 'Ứng dụng AI vào quy trình kinh doanh',
    'services.content.title': 'Marketing Nội Dung',
    'services.content.desc': 'Chiến lược và sản xuất nội dung chất lượng',
    'services.seo.title': 'SEO & Digital Marketing',
    'services.seo.desc': 'Tối ưu hóa và marketing trực tuyến',
    'services.viewAll': 'Xem Tất Cả Dịch Vụ',
    
    // About
    'about.title': 'Tại Sao Chọn D2 Group?',
    'about.experience.title': 'Kinh Nghiệm Thực Chiến',
    'about.experience.desc': 'Hơn 3 năm trong lĩnh vực tự động hóa và marketing B2B',
    'about.expertise.title': 'Chuyên Môn Đa Dạng',
    'about.expertise.desc': 'Đội ngũ chuyên gia về AI, automation, marketing và công nghệ',
    'about.results.title': 'Kết Quả Đo Lường',
    'about.results.desc': 'Cam kết ROI rõ ràng và báo cáo minh bạch',
    'about.support.title': 'Hỗ Trợ 24/7',
    'about.support.desc': 'Đồng hành cùng bạn trong suốt hành trình chuyển đổi số',
    
    // Portfolio
    'portfolio.title': 'Dự Án Tiêu Biểu',
    'portfolio.subtitle': 'Khám phá các giải pháp tự động hóa chúng tôi đã triển khai',
    'portfolio.viewMore': 'Xem Thêm Dự Án',
    
    // Contact
    'contact.title': 'Liên Hệ Với Chúng Tôi',
    'contact.subtitle': 'Sẵn sàng chuyển đổi số cùng D2 Group',
    'contact.name': 'Họ và tên',
    'contact.email': 'Email',
    'contact.phone': 'Số điện thoại',
    'contact.company': 'Công ty',
    'contact.message': 'Tin nhắn',
    'contact.send': 'Gửi Tin Nhắn',
    'contact.address': 'Địa chỉ',
    'contact.workingHours': 'Giờ làm việc',
    'contact.workingTime': 'Thứ 2 - Thứ 6: 9:00 - 18:00',
    
    // Footer
    'footer.about': 'Về D2 Group',
    'footer.aboutText': 'Chúng tôi chuyên cung cấp giải pháp tự động hóa và marketing cho doanh nghiệp B2B tại Việt Nam.',
    'footer.quickLinks': 'Liên Kết Nhanh',
    'footer.services': 'Dịch Vụ',
    'footer.legal': 'Pháp Lý',
    'footer.privacy': 'Chính Sách Bảo Mật',
    'footer.terms': 'Điều Khoản Sử Dụng',
    'footer.contact': 'Liên Hệ',
    'footer.rights': 'Bản quyền thuộc về D2 Group. Tất cả quyền được bảo lưu.',
    
    // Common
    'common.learnMore': 'Tìm Hiểu Thêm',
    'common.getStarted': 'Bắt Đầu Ngay',
    'common.readMore': 'Đọc Thêm',
    'common.viewDetails': 'Xem Chi Tiết',
    'common.backToHome': 'Quay Lại Trang Chủ',
    'common.loading': 'Đang tải...',
    'common.error': 'Đã có lỗi xảy ra',
  },
  en: {
    // Header - Điều hướng
    'nav.home': 'Trang chủ',
    'nav.services': 'Dịch vụ',
    'nav.portfolio': 'Danh mục đầu tư',
    'nav.about': 'Về chúng tôi',
    'nav.blog': 'Tin tức',
    'nav.contact': 'Liên hệ',
    
    // Hero - Phần giới thiệu chính
    'hero.title1': 'Công ty Marketing B2B',
    'hero.title2': 'Hàng đầu tại Việt Nam',
    'hero.title3': 'Dịch vụ Marketing toàn diện',
    'hero.description': 'Một công ty marketing B2B chuyên cung cấp',
    'hero.description.highlight1': 'giải pháp marketing cho doanh nghiệp',
    'hero.description.text': 'tư vấn chiến lược marketing, và',
    'hero.description.highlight2': 'dịch vụ marketing số toàn diện',
    'hero.description.end': 'cho thị trường B2B Việt Nam.',
    'hero.cta.consultation': 'Nhận tư vấn Marketing B2B miễn phí',
    'hero.cta.services': 'Xem các dịch vụ Marketing',
    'hero.stats.automations': 'Tự động hóa thành công',
    'hero.stats.roi': 'Tăng trưởng ROI',
    'hero.stats.engagement': 'Tương tác khách hàng',
    
    // Services - Dịch vụ
    'services.title': 'Dịch vụ của chúng tôi',
    'services.subtitle': 'Các giải pháp tự động hóa toàn diện cho doanh nghiệp',
    'services.chatbot.title': 'Chatbot AI & Zalo OA',
    'services.chatbot.desc': 'Tự động hóa dịch vụ khách hàng 24/7',
    'services.automation.title': 'Tự động hóa quy trình',
    'services.automation.desc': 'Tối ưu hóa quy trình làm việc và tăng năng suất',
    'services.n8n.title': 'Quy trình N8N',
    'services.n8n.desc': 'Kết nối và tự động hóa ứng dụng',
    'services.ai.title': 'Tích hợp AI',
    'services.ai.desc': 'Áp dụng AI vào quy trình kinh doanh',
    'services.content.title': 'Marketing nội dung',
    'services.content.desc': 'Chiến lược nội dung và sản xuất chất lượng',
    'services.seo.title': 'SEO & Marketing số',
    'services.seo.desc': 'Tối ưu hóa trực tuyến và marketing',
    'services.viewAll': 'Xem tất cả dịch vụ',
    
    // About - Về chúng tôi
    'about.title': 'Tại sao chọn D2 Group?',
    'about.experience.title': 'Kinh nghiệm thực tế',
    'about.experience.desc': 'Hơn 3 năm trong lĩnh vực tự động hóa và marketing B2B',
    'about.expertise.title': 'Chuyên môn đa dạng',
    'about.expertise.desc': 'Đội ngũ chuyên gia về AI, tự động hóa, marketing và công nghệ',
    'about.results.title': 'Kết quả đo lường được',
    'about.results.desc': 'Cam kết ROI rõ ràng và báo cáo minh bạch',
    'about.support.title': 'Hỗ trợ 24/7',
    'about.support.desc': 'Đồng hành cùng bạn trong suốt hành trình chuyển đổi số',
    
    // Portfolio - Danh mục dự án
    'portfolio.title': 'Dự án nổi bật',
    'portfolio.subtitle': 'Khám phá các giải pháp tự động hóa chúng tôi đã triển khai',
    'portfolio.viewMore': 'Xem thêm dự án',
    
    // Contact - Liên hệ
    'contact.title': 'Liên hệ với chúng tôi',
    'contact.subtitle': 'Sẵn sàng chuyển đổi cùng D2 Group',
    'contact.name': 'Họ và tên',
    'contact.email': 'Email',
    'contact.phone': 'Số điện thoại',
    'contact.company': 'Công ty',
    'contact.message': 'Tin nhắn',
    'contact.send': 'Gửi tin nhắn',
    'contact.address': 'Địa chỉ',
    'contact.workingHours': 'Giờ làm việc',
    'contact.workingTime': 'Thứ Hai - Thứ Sáu: 9:00 sáng - 6:00 chiều',
    
    // Footer - Chân trang
    'footer.about': 'Về D2 Group',
    'footer.aboutText': 'Chúng tôi chuyên cung cấp giải pháp tự động hóa và marketing cho doanh nghiệp B2B tại Việt Nam.',
    'footer.quickLinks': 'Liên kết nhanh',
    'footer.services': 'Dịch vụ',
    'footer.legal': 'Pháp lý',
    'footer.privacy': 'Chính sách bảo mật',
    'footer.terms': 'Điều khoản dịch vụ',
    'footer.contact': 'Liên hệ',
    'footer.rights': 'Bản quyền © D2 Group. Tất cả quyền được bảo lưu.',
    
    // Common - Chung
    'common.learnMore': 'Tìm hiểu thêm',
    'common.getStarted': 'Bắt đầu',
    'common.readMore': 'Đọc thêm',
    'common.viewDetails': 'Xem chi tiết',
    'common.backToHome': 'Quay lại trang chủ',
    'common.loading': 'Đang tải...',
    'common.error': 'Đã xảy ra lỗi',
  },
};
