// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dbukhytdpvzncgwdkjip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRidWtoeXRkcHZ6bmNnd2RramlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NDkwNTQsImV4cCI6MjA3NDUyNTA1NH0.mfGTwPTyuymLrAZHWHP5xLqB3j8Fy94vH8Iwbl2qNok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});